// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF90IWeN8Ert2CMUBbpvh_Xkj55rSKaMg',
    appId: '1:450214834298:android:4a58ea74fa5201e1c70bc3',
    messagingSenderId: '450214834298',
    projectId: 'test-36b0c',
    storageBucket: 'test-36b0c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLkLF_i92zAOitV2IN-KtxrjisqJKEw-I',
    appId: '1:450214834298:ios:18a59448300655e8c70bc3',
    messagingSenderId: '450214834298',
    projectId: 'test-36b0c',
    storageBucket: 'test-36b0c.firebasestorage.app',
    androidClientId: '450214834298-a6mit11m3iitsbfejjjbm4u6sj66d235.apps.googleusercontent.com',
    iosClientId: '450214834298-v127o69icibmqms14c23dcdut4ffb5bb.apps.googleusercontent.com',
    iosBundleId: 'com.app.moodtracker',
  );

}